spring.application.name=finalProject

server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/finalProject
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#JavaMailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT Config
jwt.signerKey =dUjIEKATZSotHhpkwqllffJR2bqQ+RRUAPjPnRZ7Uar2KXRlyNSKIZlInXdmPjvD
jwt.expiration = 3600
jwt.expirationRefreshToken = 604800
    #JWT revoke (false:limited/ true:revoke)
jwt.revoke = true

#Frontend Domain
frontend.domain = https://abcd.com/